name: 'Build processing action'
description: 'Action to build processing sketch and host artifact under GitHub release'  

inputs:
  processing_version:
    description: 'Processing language version used to built sketches'
    required: false
    default: 3.5.4
  
  target_platform:
    description: 'Targeted platform'
    required: true
    default: linux64

runs:
  using: "composite"
  steps:      
    - run: |
        mkdir -p ./processing
        wget -qO- https://download.processing.org/processing-${{ inputs.processing_version }}-linux64.tgz | tar xvz -
        ./processing-${{ inputs.processing_version }}/processing-java --help
      shell: bash
    