name: 'Build processing action'
description: 'Action to build processing sketch and host artifact under GitHub release'  

inputs:
  processing_version:
    description: 'Processing language version used to built sketches'
    required: false
    default: 3.5.4
  
  target_platform:
    description: 'Targeted platform'
    required: true
    default: linux64

runs:
  using: "composite"
  steps: 
    - run: echo ${{ inputs.processing_version }}
      shell: bash
    
    - run: echo ${{ inputs.target_platform }}
      shell: bash