name: 'Build processing action'
description: 'Action to build processing sketch and host artifact under GitHub release'  

inputs:
  sketch:
    description: 'Name of the sketch to export'
    required: true
  
  processing_version:
    description: 'Processing language version used to built sketches'
    required: false
    default: 3.5.4
  
  target_platforms:
    description: 'Space-separated list of targeted platforms'
    required: true
    default: linux64

runs:
  using: "composite"
  steps:
    - name: Install processing version ${{ inputs.processing_version }}
      run: |
        wget -q https://download.processing.org/processing-${{ inputs.processing_version }}-linux64.tgz
        tar -xzf processing-${{ inputs.processing_version }}-linux64.tgz
        rm processing-${{ inputs.processing_version }}-linux64.tgz
        echo "Processing ${{ inputs.processing_version }} installed successfully!"
      shell: bash

    - name: Build and compress distribuables...
      run: ${{ github.action_path }}/build-and-compress.sh 
      env:
        SKETCH: ${{ inputs.sketch }}
        PLATFORMS: ${{ inputs.target_platforms }}
        PROCESSING: ./processing-${{ inputs.processing_version }}/processing-java
      shell: bash
