name: 'Build processing action'
description: 'Action to build processing sketch and host artifact under GitHub release'  

inputs:
  sketch:
    description: 'Name of the sketch to export'
    required: true
  
  processing_version:
    description: 'Processing language version used to built sketches'
    required: false
    default: 3.5.4
  
  target_platform:
    description: 'Targeted platform'
    required: true
    default: linux64

runs:
  using: "composite"
  steps:
    - name: Install processing version ${{ inputs.processing_version }}.
      run: |
        wget -q https://download.processing.org/processing-${{ inputs.processing_version }}-linux64.tgz
        tar -xzf processing-${{ inputs.processing_version }}-linux64.tgz
        rm processing-${{ inputs.processing_version }}-linux64.tgz
        echo "Processing ${{ inputs.processing_version }} installed successfully!"
      shell: bash

    - name: Build and compress distribuable in-place.
      run: |
        ./processing-${{ inputs.processing_version }}/processing-java --sketch=${{ inputs.sketch }}/ --export && echo "Distribuable built for platform ${{ inputs.target_platform }}."
      shell: bash

    - name: Compress distribuable for platform ${{ inputs.sketch }}.
      run: |
        mkdir -p ./artifacts
        zip -qr ./artifacts/${{ inputs.target_platform }}.zip ./${{ inputs.sketch }}/application.${{ inputs.target_platform }}/* && echo Successfully zipped ${{ inputs.target_platform }} distribuable.
      shell: bash
