name: 'Build processing action'
description: 'Action to build processing sketch and host artifact under GitHub release'  

inputs:
  processing_version:
    description: 'Processing language version used to built sketches'
    required: false
    default: 3.5.4
  
  target_platform:
    description: 'Targeted platform'
    required: true
    default: linux64

runs:
  using: "composite"
  steps: 
    - run: echo ${{ inputs.processing_version }}
      shell: bash
    
    - run: echo ${{ inputs.target_platform }}
      shell: bash
      
    - name: Install processing version ${{ inputs.processing_version }}
      run: |
        wget https://download.processing.org/processing-${{ inputs.processing_version }}-linux64.tgz
        mkdir -p $PROCESSING_DIRECTORY
        tar xf processing-${{ inputs.processing_version }}-linux64.tgz -C $PROCESSING_DIRECTORY
        $PROCESSING_DIRECTORY/processing-${{ inputs.processing_version }}/processing-java --help
    