name: 'Build processing action'
description: 'Action to build processing sketch and host artifact under GitHub release'  

inputs:
  targets:
    description: 'Targeted platforms'
    required: true
    default:
      - windows64
      - linux64

runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/build-and-compress.sh
      shell: bash